- name: Env info
  debug: msg="This host is in {{env}} environment!!!"
- name: Add unit file for Puma
  copy:
    src: puma.service
    dest: /etc/systemd/system/puma.service
  notify: reload puma
- name: Add config for DB connection
  template:
    src: db_config.j2
    dest: /home/appuser/db_config
    group: appuser
    owner: appuser
- systemd: name=puma enabled=yes

