 - name: App deploy
   hosts: appserver
   tasks:
     - name: Fetch the latest version of application code
       git:
         repo: 'https://github.com/express42/reddit.git'
         dest: /home/appuser/reddit
         version: monolith # <-- Указываем нужную ветку
       notify: reload puma
     - name: Bundle install
       bundler:
         state: present
         chdir: /home/appuser/reddit # <-- В какой директории выполнить команду bundle
   handlers:
   - name: reload puma 
     become: true
     systemd: name=puma state=restarted
